name: Build and Deploy Client to GKE

on:
  push:
    branches: 
      - development

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: multi-cluster    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  DEPLOYMENT_NAME: gke-test # Add your deployment name here.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t client ./client

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |-
          gcloud auth configure-docker -q
          
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Push the Docker image to Google Container Registry
      - name: Push Docker Image to GCR
        env:
          IMAGE: client
        run: |-
          docker tag $IMAGE gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
          docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
      - name: kubectl CLI 
        run: |-
          kubectl version