name: Build and Deploy Client to GKE

on:
  push:
    branches: 
      - development

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: multi-cluster    # Add your cluster name here.
  GKE_ZONE: us-central1-c   # Add your cluster zone here.
  CLIENT_IMAGE: client

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |-
          gcloud auth configure-docker -q
          
      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # docker tag $CLIENT_IMAGE gcr.io/$PROJECT_ID/$CLIENT_IMAGE:$GITHUB_SHA
      # Build, Tag, and Push the Docker image to Google Container Registry
      - name: Build, Tag, Push Docker Image to GCR
        run: |-
          docker build -t gcr.io/$PROJECT_ID/$CLIENT_IMAGE:latest -t gcr.io/$PROJECT_ID/$CLIENT_IMAGE:$GITHUB_SHA -f ./client
          
          docker push gcr.io/$PROJECT_ID/$CLIENT_IMAGE:latest
          docker push gcr.io/$PROJECT_ID/$CLIENT_IMAGE:$GITHUB_SHA

      - name: Deploy Docker Image to GKE
        run: |-
          kubectl apply -f ./k8s/client-deployment.yml
          kubectl set image developments/client-deployment client=gcr.io/$PROJECT_ID/$CLIENT_IMAGE:$GITHUB_SHA